### ISSUE TITLE
Allow MIDI file renaming, toggling, deleting

### ISSUE THREAD

**Issue by wustep** [jrg94/data-viz-term-project#15]
Add support for multiple MIDI files, with:
- [x] renaming (useful for hovers later and clarity)
- [x] toggling (support max of 3? files at once)
- [x] deleting

**Comment by wustep** [comment]
Done - there still remains some issues with color when toggling things back and forth though. More exploration / decisions to be made there later..

**Comment by jrg94** [comment]
It might be easier to map the color directly to each midi file object. That way you're not looking up color from the table by index and instead grabbing it from the midi file object directly. 

Then, you could basically omit line 75 - 76:

```js
var colorScale = d3.scaleOrdinal()
    .range(colorLUT);
```

And, change line 105 to access color from the midi files list directly:

```js
.attr("fill", d => midiFiles[d.name].color);  // Line 105
```

The file list styling would need to change as well:

```js
node.style.backgroundColor = midiFiles[keys[i]].color;  // Line 143
```

The only issue from there is figuring out how to handle deletes. Maybe colors can be flagged for in use, so you only select colors that aren't in use or something like that.
