### ISSUE TITLE
Improve graph sizes / responsiveness for readability 

### ISSUE THREAD

**Issue by wustep** [jrg94/data-viz-term-project#25]
If you start the viz with a small window, the graphs can be very tiny, and some song choices make the graph unreadable -- this is cause we're using stuff like `var height = d3.select(".master-graph-pane").node().getBoundingClientRect().height;
`. Improving UI/UX exploration required here.

**Comment by wustep** [comment]
Also, there's more right padding to the graph than left!

**Comment by jrg94** [comment]
Yeah, I was looking into responsive SVG, but I'm no expert in that area. Size is essentially hacked together for now.

**Comment by wustep** [comment]
Couple options:
- play with overflow and large width/height in svg like in master graph
- just make the whole viz take up more than the current screen
- zoom buttons

**Comment by wustep** [comment]
IDEA:

So right now, there's some spacing on the right side. We can use this to create 4 vertical buttons that say "ALL", "NOTES", "FREQUENCY", and "VELOCITY". 

ALL is default. Clicking the other buttons makes that graph the primary view on the screen (taking up the entire space except the MIDI file pane).

**Comment by jrg94** [comment]
I suppose we could potentially get some feedback on this on Thursday. I don't know if I like that idea, but it does solve a lot of problems. For instance, I think that will fix load times (it's pretty slow at the moment). Also, view would definitely be better.

**Comment by wustep** [comment]
Hmm - maybe I didn't convey what I meant right. That shouldn't affect load times at all, as all the graphs are just being hidden/shown and manipulated CSS-wise.

This is what I mean (but with better styling and vertical labels):
<img width="1412" alt="Screen Shot 2019-03-19 at 2 39 35 PM" src="https://user-images.githubusercontent.com/6259534/54632984-9f7dad00-4a55-11e9-83d6-261710329429.png">
<img width="1412" alt="Screen Shot 2019-03-19 at 2 39 35 PM copy" src="https://user-images.githubusercontent.com/6259534/54632983-9f7dad00-4a55-11e9-95aa-10ea3442024a.png">

I've also doubled the master graph height here, so it's scrollable in X & Y direction, but I think this isn't really great. I think we should only allow X scrolls, and if they want more clarity they expand the graph.

Some inspiration ideas:
- https://bl.ocks.org/mbostock/34f08d5e11952a80609169b7917d4172
  - Great for master graph, but doesn't solve y-axis issue with y being too condensed.

**Comment by jrg94** [comment]
Oh okay! So, all graphs are still rendered at the same time which is slow on my machine. Not a problem. Just an opportunity for code cleanup/parallelism I figure.

Actually, I like this a lot. That way you can blow up the different graphs. Nice work!

**Comment by wustep** [comment]
Cool! I'll make the button pane things. I'll look into that inspiration option for the master graph too. 

On perf:
Graphs are rendered in <1s for me, even if there's 2M time of notes, but we can definitely look at perf in a separate issue and even just add a spinner icon animation later. 

Perf is probably caused by there being 3 separate mapping functions and them being pretty slow. We can probably do 1 run-through of the data to create mappings, and maybe combine two of them and do filtering better? Not sure

**Comment by jrg94** [comment]
Yeah, I'd say it's probably ~1s for me as well, but it just feels like everything is locked up for a moment.

I'm sure we could perform all the data analytics the first time we load in a midi file and store the results in midiFiles, so we're not doing it every time we render a graph. That said, we'd have to change up a lot of end points.

**Comment by wustep** [comment]
Moving to #30 and marking as stretch, since it's not a huge issue for now.

**Comment by wustep** [comment]
Implemented the button view in #32

**Comment by wustep** [comment]
Still more to be done here.. like using that inspiration there.

General responsiveness isn't gr8 with smaller screens
