### ISSUE TITLE
Improve Velocity over Time Graph

### ISSUE THREAD

**Issue by wustep** [jrg94/data-viz-term-project#26]
See #9 for initial prototype issue.

So this is a good start, BUT it's a little funky and difficult to interpret. 

Ideas:

- Try scatter plot instead of lines, don't sum velocity.
- Add single average line to scatter plot. Plot a point that represents the average velocity of every note played at every time. Connect these dots smoothly for the line.

Improvement:

- Add the note itself to the data so we can add it to the tooltip later. We might also want to add track number to the data too, and add these to tooltips in master/this plot.

**Comment by wustep** [comment]
Also - tooltips on mouseover?! maybe big enough for separate issue if difficult, since it's an additional enhancement

**Comment by jrg94** [comment]
Based on feedback today:

- Graph is using initial key press (type 9) velocity
- Less events/timestep = less sum
- Look into normalization
- Look into velocity over time (note starts and ends)

**Comment by wustep** [comment]
![image](https://user-images.githubusercontent.com/6259534/54799869-6f8d0000-4c35-11e9-8475-a83b2092fd5e.png)

I took on doing the MIN / MAX velocity graph, with a 0.2 opacity area in-between. Results are good but one issue is that MIDI files online tend to not be real recordings so a lot of them have constant velocities!

I'm thinking we have a toggle between this and the normalized y-axis version (where we normalize the average volume to be 1.0). But the normalized might be stretch for now..

**Comment by wustep** [comment]
See #35
