### ISSUE TITLE
Duplicate Prototype Code into Final Folder

### ISSUE THREAD

**Issue by jrg94** [jrg94/data-viz-term-project#39]
Apparently, we have to submit the prototype separate from the final version. Before we make anymore changes, we should create a copy of our work and put it into a new folder.

Prototype: https://sites.google.com/site/datavisualizationspring2019/term-project/project-prototype
Piazza: https://piazza.com/class/jqq33mm5jmr657?cid=48

**Comment by wustep** [comment]
Ooh, good idea. Do we use [the version that we presented in class](https://github.com/jrg94/data-viz-term-project/commit/67e46aafda55e2e4e9d3a9192a21a70d141c7860)?

**Comment by jrg94** [comment]
Yeah, that's probably a good plan.

**Comment by wustep** [comment]
Hmmm - it might take some git magic to preserve history.. Wanna tackle this? Let's put the latest version of the code in `src` and revert the current version in `prototype`?

**Comment by jrg94** [comment]
Actually, the final prototype isn't due until 4/6, so maybe we can hold off until then. Though, I'm not sure. The class looked at one version, and we already have a different graph and styling. Hmmm.

**Comment by jrg94** [comment]
As a follow up, prototype evaluation is due on 4/11. We may be able to start versioning our prototypes. I'll see if GitHub pages has a way of showing different versions from git tags.

**Comment by wustep** [comment]
Yep - I agree with seeing if GH pages supports showing the older version. I think we should just migrate `prototype` to `src` going forward

**Comment by jrg94** [comment]
Good plan. I might try some git magic. Let me do some research.

**Comment by jrg94** [comment]
Is [this](https://github.com/jrg94/data-viz-term-project/commit/67e46aafda55e2e4e9d3a9192a21a70d141c7860) the last commit you made to master before the presentation?

**Comment by wustep** [comment]
Yep!
