### ISSUE TITLE
Rename Project

### ISSUE THREAD

**Issue by jrg94** [jrg94/data-viz-term-project#41]
Do you want to rename this repo at some point? 😆

**Comment by wustep** [comment]
Tbd, need a cool name :)

**Comment by jrg94** [comment]
Agreed!

**Comment by wustep** [comment]
let's go ahead and rename to "JuxtaMIDI". 

title - "JuxtaMIDI - Pinpointing Mistakes in MIDI Practice Recordings"

**Comment by jrg94** [comment]
Links may be broken now, but name has been changed.

**Comment by jrg94** [comment]
I think we'll need to resubmit the prototype.

**Comment by jrg94** [comment]
Nevermind. Redirects seem automatic.
