### ISSUE TITLE
Add Position Marker to Master Graph X-Axis

### ISSUE THREAD

**Issue by jrg94** [jrg94/data-viz-term-project#42]
Looks like it might be relatively easy to create a callback function while the song is playing for updating the UI: https://www.npmjs.com/package/midi-player-js

**Comment by wustep** [comment]
That's the one we're using already!

https://github.com/grimmdude/MidiPlayerJS

**Comment by jrg94** [comment]
Yeah, that's what I mean. It should be easy to write the callback function. Only issue is mapping the tick # to our axis. They have an example in the documentation on the page.

**Comment by jrg94** [comment]
Forgot to close this!
