### ISSUE TITLE
Allow MIDI Playback

### ISSUE THREAD

**Issue by wustep** [jrg94/data-viz-term-project#5]
Just thought of this -- pretty obvious idea but we should allow MIDI playback and add a cursor on Graph 1 that follows where the player is at (if easily done).

**Comment by jrg94** [comment]
Yeah, so this was something I mentioned in our meeting with Professor Chen as “real-time” playback. I was thinking about showing a subset of the graph and shifting it over time, but it’s a good plan either way. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wustep** [comment]
Adding a play button near the file pane icons would be good here :)

**Comment by wustep** [comment]
Added with #33. Pretty basic, lots of bugs (like it'll just keep playing if you delete, etc.) and not linked to cursor, but good for now :)

**Comment by wustep** [comment]
Fixed pause bugs, made pause actually pause instead of stop;  #34. We can still improve by adding cursor and stuff, but that's definitely hard and stretch

**Comment by jrg94** [comment]
Cursor might be easier than you think (at least from a D3 point of view). I'm not sure how you get the live time information though.
