### ISSUE TITLE
Create MIDI Loading Script Prototype

### ISSUE THREAD

**Issue by jrg94** [jrg94/data-viz-term-project#6]
I imagine we'd need to use: https://github.com/mudcube/MIDI.js

**Comment by jrg94** [comment]
I've been looking into this a little bit. I imagine we'd just want to load the user's MIDI files locally in the browser. We're not trying to host them on a server anywhere.

This looks like a good place to start: https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_fileupload_files

**Comment by jrg94** [comment]
I'll take this for now. Making the upload branch.

**Comment by wustep** [comment]
See: https://github.com/wustep/chorus/blob/chorus/public/demo/midi/js/player.js

**Comment by jrg94** [comment]
I used a simple input form and the midi parser library. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
